# Time to wait for the client to send back their mod list before kicking them.
# If the delay is too short, clients may not have enough time to send their response, depending on their internet.
# If the delay is too long, clients may hang around for too long.
# The player's movement, actions and chat messages are frozen at this time.
[grace]
# The reason for kicking a player due to them not responding to the server's request.
disconnectMessage = "You were kicked for not sending a response to the anticheat!\nThis is probably due to missing the anticheat client mod.\nInstall it here: https://modrinth.com/mod/inertiaanticheat"

[mods]
# Accepted types: "individual", "group"
method = "individual"
# Accepted algorithms: "MD5", "SHA1", "SHA256"
algorithm = "MD5"

[mods.individual]
# Immediately kick players who have these mods in their modlist.
# The mod checks (and kicks) for blacklisted mods first.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
blacklist = ["Wurst Client", "Meteor Client"]
# The reason for kicking a player due to having blacklisted mods installed.
# Use ${blacklisted} as a placeholder for all blacklisted mods found on the player.
blacklistMessage = "You were kicked for having illegal mods installed!\nRemove ${blacklisted} before rejoining the server."

# Immediately kick players who do not have these mods in their modlist.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
whitelist = []
# The reason for kicking a player due to not having whitelisted mods installed.
# Use ${whitelisted} as a placeholder for all whitelisted mods not found on the player.
whitelistMessage = "You were kicked for having not having required mods installed!\nInstall ${whitelisted} before rejoining the server."

[mods.group]
# The hash for the server to check against. See "showHash" for more details.
# Filling this will cause the server to disreguard blacklisted/whitelisted mods.
# Soft whitelisted mods (see below) will still be checked.
# You can add multiple hashes into the list, and the server will check against all of them.
hash = []
# The reason for kicking a player due to their modlist hash not matching up.
hashMessage = "You were kicked for not matching the server's modlist!\nDid you install their modpack correctly?"

# Allow certain mods to be used by players, in addition to your modpack.
# This allows players to make use of optional client mods if you allow it.
softWhitelist = []

[e2ee]
# Enable using end-to-end encryption to encrypt modlists coming from clients.
# This prevents outside sources from reading and modifying modlists coming from clients.
# This doesn't prevent clients from modfiying their own modlists though.
enable = false

# Name of the private and public key files to use for E2EE.
# DO NOT LEAK YOUR PRIVATE KEY!
privateKeyName = "private.key"
publicKeyName = "public.key"

# The reason for kicking a player due to them disabling support for E2EE.
unsupportedMessage = "The server is using E2EE, but you have disabled support for E2EE!\nPlease look in your config file for more information."

[debug]
# Show additional information in server logs.
debug = false
# do not touch pls :)
version = 5