# IMPORTANT!
# Please check https://github.com/DiffuseHyperion/InertiaAntiCheat/wiki/Modern-(Version-1.0.0-and-above) on how to configure this mod.
# You will likely need https://iac.diffusehyperion.com/ in the process of configuring this mod.
[mods]
# The hashing algorithm for the mod to use.
# MD5 is the fastest but most insecure.
# SHA256 is the slowest but most secure.
# Accepted algorithms: "MD5", "SHA1", "SHA256"
algorithm = "MD5"
# Whether to only check for mod names, or the data of client mods when clients join the server.
# Checking only names is much quicker and preferred on large modpacks, but is inherently less secure.
# The kick message to show to clients when they try to connect without InertiaAntiCheat installed.
vanillaKickMessage = "You were kicked for not sending a response to the anti-cheat!\nThis is probably due to missing the anti-cheat client mod.\nInstall it here: https://modrinth.com/mod/inertiaanticheat"
# The kick message to show to clients when they fail the modlist check.
deniedKickMessage = "You were kicked by the anti-cheat!\nThis is due to having illegal mods.\nPlease contact your server administrator for more details."

[transfer]
# The method for client's to use to transfer their modlist to the server.
# Clients can send the entirety of their mods to the server. This is more secure.
# Clients can also only send the name of their mods only to the server. This is much quicker and prefered with large modpacks.
# Accepted types: "data", "name"
method = "data"

[validation]
# The method to check client's mod list.
# If you prefer blacklisting/whitelisting certain mods from being used, use "individual".
# If you prefer ensuring client's have a modpack installed, use "group".
# Accepted types: "individual", "group"
method = "individual"

[validation.individual]
# Immediately kick players who have these mods in their modlist.
# The mod checks (and kicks) for blacklisted mods first.
blacklist = []
# Immediately kick players who do not have these mods in their modlist.
whitelist = []

[validation.group]
# The hash for the server to check against.
# You can add multiple hashes into the list, and the server will check against all of them.
hash = []
# Allow certain mods to be used by players, in addition to your modpack.
# This allows players to make use of optional client mods if you allow it.
softWhitelist = []

[motd]
# Whether to show an icon on client's server list indicating that InertiaAntiCheat is installed.
showInstalled = true
# The names of blacklisted mods to report to clients.
# Clients will be able to see these mod names in their server browser.
# You may choose to put arbituary names, extra names, fake names or no names at all here.
# Setting this to be an empty list will cause the icon to not show up.
blacklist = ["Banned mods: ", "None"]
# The names of whitelisted mods to report to clients.
# Clients will be able to see these mod names in their server browser.
# You may choose to put arbituary names, fake names or no names at all here.
# Setting this to be an empty list will cause the icon to not show up.
whitelist = ["Whitelisted mods: ", "None"]
# The name of the modpack to report to clients.
# Clients will be able to see the modpack name in their server browser.
# Setting this to be an empty list will cause the icon to not show up.
hash = ["Requires modpack: ", "Modpack Name"]

[debug]
# Show additional information in server logs.
debug = false
# do not touch pls :)
version = 8