[mods]
# Accepted types: "individual", "group"
method = "individual"
# Accepted algorithms: "MD5", "SHA1", "SHA256"
algorithm = "MD5"

[mods.individual]
# Immediately kick players who have these mods in their modlist.
# The mod checks (and kicks) for blacklisted mods first.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
blacklist = ["c20218d611730cfd0eb000897e6968fd"]

# Immediately kick players who do not have these mods in their modlist.
# Enabling debug will show the full modlist of players joining, allowing you to discover mod names.
whitelist = []

[mods.group]
# The hash for the server to check against. See "showHash" for more details.
# Filling this will cause the server to disreguard blacklisted/whitelisted mods.
# Soft whitelisted mods (see below) will still be checked.
# You can add multiple hashes into the list, and the server will check against all of them.
checksum = []

# Allow certain mods to be used by players, in addition to your modpack.
# This allows players to make use of optional client mods if you allow it.
softWhitelist = []

[debug]
# Show additional information in server logs.
debug = false
# do not touch pls :)
version = 5